title: ""                     # optional
theme: jekyll-theme-cayman    # any official theme is fine
show_downloads: false         # optional

markdown: kramdown
kramdown:
  math_engine: katex          # <— tells kramdown to hand math to KaTeX

include: ["_includes/head-custom.html"]
